id: I97B16E5E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T04:36:25+00:00'
last_modified: '2022-06-08T01:22:44.769483+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7991
  title: སྐྱེས་ཆེན་གྱི་བཞུད་ལམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    106F:
      image_group_id: I3CN7993
      title: ''
      total_pages: 260
      order: 1
      base_file: 106F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
