id: P004479
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN7991
  title: སྐྱེས་ཆེན་གྱི་བཞུད་ལམ།
  author: ''
  volumes:
    19a6c0ea446043c5b6f4e6b50f82433a:
      image_group_id: I3CN7993
      title: ''
      volume_number: 1
      total_pages: 260
      base_file: v001.txt
